# Generated by Django 2.2 on 2019-05-31 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_a', models.DateTimeField(auto_now_add=True)),
                ('hora_c', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='cerrado', max_length=10)),
                ('monto_inicial', models.IntegerField()),
                ('monto_final', models.IntegerField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
