# Generated by Django 2.2 on 2019-05-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='estado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='hora_a',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='hora_c',
            field=models.DateTimeField(blank=True),
        ),
    ]
