# Generated by Django 2.2 on 2019-06-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20190530_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='monto_final',
            field=models.IntegerField(blank=True),
        ),
    ]
