# Generated by Django 2.2 on 2019-06-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20190601_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='hora_c',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
