# Generated by Django 2.2.2 on 2019-06-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20190601_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='caja_modulo',
            field=models.CharField(default='amargo', max_length=20),
            preserve_default=False,
        ),
    ]
