# Generated by Django 2.2.2 on 2019-06-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecompra',
            old_name='precio_unitario',
            new_name='precio_compra_unitario',
        ),
    ]
