# Generated by Django 2.2 on 2019-05-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimiento', '0002_compra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pmp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
