# Generated by Django 2.2.2 on 2019-06-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimiento', '0003_auto_20190623_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
