# Generated by Django 2.2 on 2019-05-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimiento', '0004_producto_margen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pmp',
            field=models.IntegerField(editable=False),
        ),
    ]
