# Generated by Django 2.2 on 2019-05-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimiento', '0005_auto_20190524_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pmp',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_actual',
            field=models.IntegerField(default=0),
        ),
    ]
