# Generated by Django 2.2.2 on 2019-06-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimiento', '0006_auto_20190530_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='fecha_vencimiento',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='lote',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
